name: voxcad2
base: core18 # the base snap is the execution environment for this snap
version: '2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Design your voxel-based soft robot
description: |
  VoxCAD is the GUI that wraps around voxelize and allows you to construct, edit and simulate objects composed of voxels (bricks).
  Refer to: https://www.creativemachineslab.com/voxcad.html

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j 10
      make install
    build-packages:
      - libssl-dev
  voxcad2:
    after: [cmake]
    plugin: make
    source: https://github.com/liusida/VoxCAD
    source-type: git
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 10
      make install
    build-packages:
      - g++
      - qt5-default
      - libglfw3-dev
      - freeglut3-dev
      - libglm-dev
      - mesa-utils
      - zlib1g-dev
      - libqt5opengl5-dev

apps:
  voxcad2:
    command: bin/voxcad2
    extensions:
      - kde-neon
      - opengl
      
    